DEFAULT_FILE_STORAGE = 'storages.backends.s3.S3Storage'
AWS_ACCESS_KEY_ID = "AKIAJMIPQKECN7ZJRM5A"
AWS_SECRET_ACCESS_KEY = "AWSSecretKey=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"
AWS_STORAGE_BUCKET_NAME = "feelkm-assets"